name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 21 1 * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
# The job below generates the images displayed on lowlighter/lowlighter
# You can reuse these steps if you want to have a profile page similar to mine.
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugin_isocalendar: yes
          config_timezone: Europe/Paris
          config_order: base.header, isocalendar, base.repositories
          config_padding: 10%
          use_prebuilt_image: master 
          
      - name: Personal metrics (additional)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.additional.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_skipped: lowlighter
          plugin_stargazers: yes
          config_timezone: Europe/London
          config_order: languages, pagespeed, habits, stargazers, stars
          use_prebuilt_image: master
          plugin_topics: yes
          plugin_topics_sort: stars
          # plugin_topics_mode: mastered
          plugin_topics_limit: 15
          plugin_stars: yes
          plugin_stars_limit: 2
